spring:
  profiles:
    active:
      - dev
---
server:
  port: 8080
  
mybatis:
  mapper-locations: 
  - classpath:mapping/*.xml
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/21springcloud?serverTimezone=GMT%2B8 
    username: root  
    password: root 
    
  application:
    name: config-product-client
  profiles: dev

    
eureka:
  client:                 
    service-url:
      defaultZone: http://jay:123@localhost:7002/eureka 
      # defaultZone: http://jay:123@eureka1:7001/eureka,http://jay:123@eureka2:7002/eureka,http://jay:123@eureka3:7003/eureka  

  instance:
    instance-id: config-product-client
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 2 
#    lease-expiration-duration-in-seconds: 5  

# springboot actuator
info:
  app.name: config-product-client
  company.name: jay
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
logging:
  level:
    com.jay.mapper: debug
    
# HystrixDashboard
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
server:
  port: 8081
  
mybatis:
  mapper-locations: 
  - classpath:mapping/*.xml
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/21springcloud?serverTimezone=GMT%2B8 
    username: root  
    password: root  
    
  application:
    name: config-product-client
  profiles: beta
 
 
eureka:
  client:                 
    service-url:
      defaultZone: http://jay:123@localhost:7002/eureka 
      # defaultZone: http://jay:123@eureka1:7001/eureka,http://jay:123@eureka2:7002/eureka,http://jay:123@eureka3:7003/eureka  # ¼¯Èºeureka

  instance:
    instance-id: config-product-client
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 2 
#    lease-expiration-duration-in-seconds: 5  

# springboot actuator
info:
  app.name: config-product-client
  company.name: jay
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
logging:
  level:
    com.jay.mapper: debug
    
# HystrixDashboard
management:
  endpoints:
    web:
      exposure:
        include: '*'
