spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201

spring: 
  profiles: dev
  application: 
    name: config-client-test

eureka:
  client:
    service-url:
      defaultZone: http://jay:123@localhost:7301/eureka
      
info:
  app.name: config-client-dev
  company.name: jay

---
server:
  port: 8102

spring:
  profiles: beta
  application: 
    name: config-client-test

eureka:
  client:
    service-url:
      defaultZone: http://jay:123@localhost:7301/eureka
 
info:
  app.name: config-client
  company.name: jay
